import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-surface':  'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-inverse':  'var(--bg-inverse)',
        'bg-muted':    'var(--bg-muted)',
        fg: 'var(--fg)',
        'fg-muted':    'var(--fg-muted)',
        'fg-subtle':   'var(--fg-subtle)',
        'fg-inverse':  'var(--fg-inverse)',
        'fg-on-accent':'var(--fg-on-accent)',
        border:          'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-subtle': 'var(--border-subtle)',
        accent:          'var(--accent)',
        'accent-hover':  'var(--accent-hover)',
        'accent-press':  'var(--accent-press)',
        'accent-strong': 'var(--accent-strong)',
        'accent-deep':   'var(--accent-deep)',
        neutral: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          150: 'var(--color-neutral-150)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          850: 'var(--color-neutral-850)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        lime: {
          300: 'var(--color-lime-300)',
          400: 'var(--color-lime-400)',
          500: 'var(--color-lime-500)',
          800: 'var(--color-lime-800)',
          950: 'var(--color-lime-950)',
        },
        'accent-blue':   'var(--color-accent-blue)',
        'accent-purple': 'var(--color-accent-purple)',
        'accent-clay':   'var(--color-accent-clay)',
      },
      fontFamily: {
        sans:  ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-instrument-serif)', 'serif'],
        mono:  ['var(--font-geist-mono)', 'monospace'],
      },
      fontSize: {
        '2xs':  ['0.6875rem', { lineHeight: '1.4' }],
        xs:     ['0.75rem',   { lineHeight: '1.4' }],
        sm:     ['0.875rem',  { lineHeight: '1.4' }],
        base:   ['1rem',      { lineHeight: '1.6' }],
        md:     ['1.125rem',  { lineHeight: '1.6' }],
        lg:     ['1.375rem',  { lineHeight: '1.4' }],
        xl:     ['1.75rem',   { lineHeight: '1.2' }],
        '2xl':  ['2.25rem',   { lineHeight: '1.15' }],
        '3xl':  ['3rem',      { lineHeight: '1.05' }],
        '4xl':  ['4rem',      { lineHeight: '1.05' }],
        '5xl':  ['5.5rem',    { lineHeight: '1.05' }],
        '6xl':  ['7.5rem',    { lineHeight: '1' }],
        '7xl':  ['10rem',     { lineHeight: '1' }],
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight:   '-0.02em',
        wide:    '0.02em',
        wider:   '0.06em',
        widest:  '0.12em',
      },
      spacing: {
        '7': '3rem', '8': '4rem', '9': '6rem', '10': '8rem',
        '11': '12rem', '12': '16rem',
      },
      borderRadius: {
        xs: '2px', sm: '4px', md: '8px',
        lg: '12px', xl: '20px', '2xl': '32px',
      },
      boxShadow: {
        xs:   '0 1px 2px 0 rgb(0 0 0 / 0.04)',
        sm:   '0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        md:   '0 4px 12px -2px rgb(0 0 0 / 0.10), 0 2px 4px -2px rgb(0 0 0 / 0.06)',
        lg:   '0 12px 24px -6px rgb(0 0 0 / 0.12), 0 4px 8px -4px rgb(0 0 0 / 0.06)',
        xl:   '0 24px 48px -12px rgb(0 0 0 / 0.18)',
        'glow-lime': '0 0 0 1px rgb(211 250 83 / 0.4), 0 8px 32px -4px rgb(211 250 83 / 0.25)',
      },
      transitionDuration: {
        fast:    '120ms',
        base:    '240ms',
        slow:    '400ms',
        slower:  '640ms',
        deliberate: '1000ms',
      },
      transitionTimingFunction: {
        'out-expo':  'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out-exp':'cubic-bezier(0.83, 0, 0.17, 1)',
        'spring':    'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
};

export default config;
